# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: BioPy

on:
  repository_dispatch:
    types: [start-build]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.sha }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Output Run ID
      run: echo ${{ github.run_id }}

    - name: Output Run Number
      run: echo ${{ github.run_number }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools --upgrade
        pip install -r requirements.txt
      working-directory: D:\a\BioPy\BioPy

    - name: Update build/version number
      run: |
        python semvar.py ${{ github.run_number }}
        python updateVersion.py
        $version= Get-Content version.txt -Tail 1
        echo "version_number=$version" >> $GITHUB_ENV
        # echo "::set-env name=VERSION::$version"

    - name: Test with pytest
      run: |
        pytest
      working-directory: tests

    - name: Pyinstaller
      run: pyinstaller gui.spec
      working-directory: src

    # - name: Upload pyinstaller artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: test
    #     path: src/dist

    # - name: Download pyinstaller artifact
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: test
    #     path: src/dist

    # - name: Display structure of downloaded files
    #   run: dir
    #   working-directory: src/dist/gui
        
    - name: Compile iss script
      run: ./iscc BioPy_Setup.iss
      working-directory: scripts
      shell: pwsh
      
    - name: Set env
      run: |
        echo "color=yellow" >> $GITHUB_ENV
      
    - name: Test
      run: echo ${{ env.color }}

    - name: Upload setup.exe artifact
      uses: actions/upload-artifact@v2
      with:
        name: BioPy_Setup_
        path: src\dist\gui\BioPy_Setup_*\BioPy_Setup_* 
