# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: BioPy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Output Run ID
      run: echo ${{ github.run_id }}

    - name: Output Run Number
      run: echo ${{ github.run_number }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools --upgrade
        pip install -r requirements.txt
      working-directory: D:\a\BioPy\BioPy

    - name: Update build/version number
      run: |
        python semvar.py ${{ github.run_number }}
        python updateVersion.py
        $version= Get-Content version.txt -Tail 1
        echo "::set-env name=VERSION::$version"

    - name: Test with pytest
      run: |
        pytest
      working-directory: tests

    - name: Pyinstaller
      run: pyinstaller gui.spec
      working-directory: src

    # - name: Upload pyinstaller artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: test
    #     path: src/dist

    # - name: Download pyinstaller artifact
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: test
    #     path: src/dist

    # - name: Display structure of downloaded files
    #   run: dir
    #   working-directory: src/dist/gui
        
    - name: Compile iss script
      run: ./iscc BioPy_Setup.iss
      working-directory: scripts
      shell: pwsh

    # - name: Sign setup.exe
    #   uses: dlemstra/code-sign-action@v1
    #   with:
    #     certificate: '${{ secrets.CERTIFICATE }}'
    #     folder: 'src\dist\gui\setup\mysetup.exe'
    #     recursive: false

    - name: Upload setup.exe artifact
      uses: actions/upload-artifact@v2
      with:
        name: BioPy_Setup_${{ env.VERSION }}
        path: src\dist\gui\BioPy_Setup_*\BioPy_Setup_*
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

